export const BLOG_LIST_REQUEST = "BLOG_LIST_REQUEST"; 
export const BLOG_LIST_SUCCESS = "BLOG_LIST_SUCCESS"; 
export const BLOG_LIST_FAIL = "BLOG_LIST_FAIL"; 

export const BLOG_CREATE_REQUEST = "BLOG_CREATE_REQUEST"; 
export const BLOG_CREATE_SUCCESS = "BLOG_CREATE_SUCCESS"; 
export const BLOG_CREATE_FAIL = "BLOG_CREATE_FAIL"; 
export const BLOG_CREATE_RESET = "BLOG_CREATE_RESET"; 

export const BLOG_EDIT_REQUEST = "BLOG_EDIT_REQUEST"; 
export const BLOG_EDIT_SUCCESS = "BLOG_EDIT_SUCCESS"; 
export const BLOG_EDIT_FAIL = "BLOG_EDIT_FAIL"; 
export const BLOG_EDIT_RESET = "BLOG_EDIT_RESET"; 