export const COMMENT_CREATE_REQUEST = "COMMENT_CREATE_REQUEST";
export const COMMENT_CREATE_SUCCESS = "COMMENT_CREATE_SUCCESS";
export const COMMENT_CREATE_FAIL = "COMMENT_CREATE_FAIL";

export const COMMENT_EDIT_REQUEST = "COMMENT_EDIT_REQUEST";
export const COMMENT_EDIT_SUCCESS = "COMMENT_EDIT_SUCCESS";
export const COMMENT_EDIT_FAIL = "COMMENT_EDIT_FAIL";

export const COMMENT_DELETE_REQUEST = "COMMENT_DELETE_REQUEST";
export const COMMENT_DELETE_SUCCESS = "COMMENT_DELETE_SUCCESS";
export const COMMENT_DELETE_FAIL = "COMMENT_DELETE_FAIL";