export const FOLLOW_LIST_REQUEST = "FOLLOW_LIST_REQUEST";
export const FOLLOW_LIST_SUCCESS = "FOLLOW_LIST_SUCCESS";
export const FOLLOW_LIST_FAIL = "FOLLOW_LIST_FAIL";

export const FOLLOW_ADD_REQUEST = "FOLLOW_ADD_REQUEST";
export const FOLLOW_ADD_SUCCESS = "FOLLOW_ADD_SUCCESS";
export const FOLLOW_ADD_FAIL = "FOLLOW_ADD_FAIL";
export const FOLLOW_ADD_RESET = "FOLLOW_ADD_RESET";



