export const POSTING_LIST_REQUEST = "POSTING_LIST_REQUEST"; 
export const POSTING_LIST_SUCCESS = "POSTING_LIST_SUCCESS"; 
export const POSTING_LIST_FAIL = "POSTING_LIST_FAIL"; 

export const POSTING_DETAILS_REQUEST = "POSTING_DETAILS_REQUEST"; 
export const POSTING_DETAILS_SUCCESS = "POSTING_DETAILS_SUCCESS"; 
export const POSTING_DETAILS_FAIL = "POSTING_DETAILS_FAIL"; 

export const POSTING_CREATE_REQUEST = "POSTING_CREATE_REQUEST"; 
export const POSTING_CREATE_SUCCESS = "POSTING_CREATE_SUCCESS"; 
export const POSTING_CREATE_FAIL = "POSTING_CREATE_FAIL"; 
export const POSTING_CREATE_RESET = "POSTING_CREATE_RESET"; 

export const POSTING_UPDATE_REQUEST = "POSTING_UPDATE_REQUEST"; 
export const POSTING_UPDATE_SUCCESS = "POSTING_UPDATE_SUCCESS"; 
export const POSTING_UPDATE_FAIL = "POSTING_UPDATE_FAIL"; 
export const POSTING_UPDATE_RESET = "POSTING_UPDATE_RESET"; 

export const POSTING_DELETE_REQUEST = "POSTING_DELETE_REQUEST"; 
export const POSTING_DELETE_SUCCESS = "POSTING_DELETE_SUCCESS"; 
export const POSTING_DELETE_FAIL = "POSTING_DELETE_FAIL"; 

export const POSTING_LIKE_REQUEST = "POSTING_LIKE_REQUEST";
export const POSTING_LIKE_SUCCESS = "POSTING_LIKE_SUCCESS";
export const POSTING_LIKE_FAIL = "POSTING_LIKE_FAIL";
